---
title: "Pacoima Beautiful Soil Samples"
author: "USC Environmental Health Center"
output: html_document
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(ggmap)
library(leaflet)
library(readxl)

```

```{r All PB Sites, message=FALSE, warning=FALSE, echo=FALSE}
PB_SoilDataRegistry <- read_csv("CSVFiles/PB_SoilDataRegistry.csv")%>%
  select(!c(`...20`, `...21`, `...22`))

```

```{r Soil Batches, message=FALSE, warning=FALSE, echo=FALSE}
# Batch 1
Batch1_SamplesPB2022 <- read_csv("CSVFiles/Batch1_SamplesPB2022.csv")%>%
  select(!`...4`)%>%
  filter(!is.na(`Average Pb (ppm)`))

Batch1_SamplesPB2022 <- Batch1_SamplesPB2022%>%
  mutate(Site_ID = case_when(SAMPLE == "pb.4.10753sutter.1" ~ "PB.4.10753Sutter.1",
                             SAMPLE == "pb.4.10753sutter.2" ~ "PB.4.10753Sutter.2",
                             SAMPLE == "pb.4.10753sutter.3" ~ "PB.4.10753Sutter.3",
                             SAMPLE == "pb.dmgpark.4" ~ "PB.4.DavidGonzalesPark.4",
                             SAMPLE == "pb.dmgpark.5" ~ "PB.4.DavidMGonzalesPark.5",
                             SAMPLE == "pb.dmgpark.6" ~ "PB.4.DavidMGonzalesPark.6",
                             SAMPLE == "pb.dmgpark.7" ~ "PB.4.DavidMGonzalesPark.7",
                             SAMPLE == "pb.dmgpark.8" ~ "PB.4.DavidMGonzalesPark.8",
                             SAMPLE == "pb.413073carl322.1" ~ "PB.4.13073Carlst322.1",
                             SAMPLE == "pb.413073carl322.2" ~ "PB.4.13073Carlst322.2",
                             SAMPLE == "pb.413073carl322.3" ~ "PB.4.13703CarlSt322.3", #PB.4.13073CarlSt322.3
                             SAMPLE == "pb.413073carl322.4" ~ "PB.4.13073CarlSt322.4",
                             SAMPLE == "pb.4.4.1" ~ "PB.4.13009Pierce.1", # Here on, sample id is site id in
                             SAMPLE == "pb.4.4.2" ~ "PB.4.13009Pierce.2", # ArcGIS survey 123
                             SAMPLE == "pb.4.4.3" ~ "PB.4.13009Pierce.3",
                             SAMPLE == "pb.4.2.1" ~ "PB.4.10656SutterAve.1",
                             SAMPLE == "pb.4.2.2" ~ "PB.4.10656SutterAve.2",
                             SAMPLE == "pb.4.2.3" ~ "PB.4.10656SutterAve.3"))

PB_SoilBatch1_merge <- merge(PB_SoilDataRegistry%>%
          rename("Site_ID" = "Site (Household) ID"),
      Batch1_SamplesPB2022, by = "Site_ID", all.x = TRUE)

# Batch 2
Batch2_SamplesPB2022 <- read_csv("CSVFiles/Batch2_SamplesPB2022.csv")%>%
  select(SAMPLE, LOCATION, Pb, `Average (ppm)`)%>%
  filter(!is.na(`Average (ppm)`))

# ! PB.4.12851Pierce108.3 is in ArcGIS Survey 123, but not in PB_SoilDataRegistry

Batch2_SamplesPB2022 <- Batch2_SamplesPB2022%>%
  mutate(Site_ID = case_when(SAMPLE == "PB108.1" ~ "PB.4.12851Pierce108.1",
                             SAMPLE == "PB108.2.3" ~ "PB.4.12851Pierce108.2",
                             SAMPLE == "PB120.1.3" ~ "PB.4.12877Pierce120.1",
                             SAMPLE == "PB120.2.3" ~ "PB.4.12877Pierce120.2",
                             SAMPLE == "PB120.3.3" ~ "PB.4.12877Pierce120.3",
                             SAMPLE == "PB106.1.3" ~ "PB.4.12853Pierce106.1",
                             SAMPLE == "PB106.2.3" ~ "PB.4.12853Pierce106.2",
                             SAMPLE == "PB106.3.3" ~ "PB.4.12851Pierce106.3",
                             SAMPLE == "PB1.3" ~ "PB.4.13508Piercest.1",
                             SAMPLE == "PB2.3" ~ "PB.4.13508Pierce.2",
                             SAMPLE == "PB3.2" ~ "PB.4.13058Pierce.3")) # searched address in Survey123

# merge(PB_SoilBatch1_merge, Batch2_SamplesPB2022, by = "Site_ID", all.x = TRUE,
#       suffixes = c(".Batch1", ".Batch2"))%>%
#     View()

# Batch 3
Batch3_SamplesPB2022 <- read_csv("CSVFiles/Batch3_SamplesPB2022.csv")%>%
  select(SAMPLE, LOCATION, `Average (in ppm)`)%>%
  filter(!is.na(`Average (in ppm)`))

Batch3_SamplesPB2022 <- Batch3_SamplesPB2022%>%
  mutate(Site_ID = case_when(SAMPLE == "PB12905" ~ "PH.4.12905Pierce140.1",
                             SAMPLE == "PB12905.2" ~ "PB.4.12905Pierce140.2",
                             SAMPLE == "PB12905.3" ~ "PB.4.12905Pierce140.3",
                             SAMPLE == "PB10909.1" ~ "PB.4.10909Pierce411.1",
                             SAMPLE == "PB10909.2" ~ "PB.4.10909Pierce411.2",
                             SAMPLE == "PB10909.3" ~ "PB.4.10909Pierce411.3"))

# merge(merge(PB_SoilBatch1_merge, Batch2_SamplesPB2022, by = "Site_ID", all.x = TRUE,
#       suffixes = c(".Batch1", ".Batch2")),
#       Batch3_SamplesPB2022, by = "Site_ID", all.x = TRUE, suffixes = c("", ".Batch3"))%>%
#   View()

# Batch 4
Batch4_SamplesPB2022 <- read_csv("CSVFiles/Batch4_SamplesPB2022.csv")%>%
  select(SAMPLE, LOCATION, `Average (ppm)`)%>%
  filter(!is.na(`Average (ppm)`))

Batch4_SamplesPB2022 <- Batch4_SamplesPB2022%>%
  mutate(Site_ID = case_when(SAMPLE == "PB10662" ~ "PB.4.10662SutterAve.1",
                             SAMPLE == "PB10662.2" ~ "PB.4.10662SutterAve.2",
                             SAMPLE == "PB10662.3" ~ "PB.4.10662SutterAve.3",
                             SAMPLE == "PBAFF" ~ "Pb.4.AmericanFruitsandFlavors.1",
                             SAMPLE == "PBAFF.2" ~ "PB.4.AmericanFruitsandflavors.2",
                             SAMPLE == "PBAFF.3" ~ "PB.4.AmericanFruitsandFlavors.3",
                             SAMPLE == "PB13110" ~ "Pb.4.13110JouetteSt.1",
                             SAMPLE == "PB13110.2" ~ "PB.4.13110 Jouett St.2",
                             SAMPLE == "PB13110.3" ~ "PB.4.13110 Jouett St.3",
                             SAMPLE == "PB13064" ~ "Pb.4.13064JouettSt.1",
                             SAMPLE == "PB13064.2" ~ "Pb.4.13064JouettSt.2",
                             SAMPLE == "PB13064.3" ~ "Pb.4.13064JouettSt.3"))
```

```{r Batch Site Additions, message=FALSE, warning=FALSE, echo=FALSE}
BatchAdd <- read_excel("C:/Users/bcruiz/OneDrive - University of Southern California/Attachments/BatchesMerged_jj.xlsx")%>%
  select(-c(Sample, Average))

```

```{r Pacoima Beautiful 5, message=FALSE, warning=FALSE, echo=FALSE}
Pacoima_Beautiful5 <- read_excel("C:/Users/bcruiz/OneDrive - University of Southern California/PB/Soil_XRF/CSVFiles/Pacoima_Beautiful5.xlsx")%>%
  select(SAMPLE, LOCATION, Pb)%>%
  group_by(SAMPLE)%>%
  mutate(Average = mean(Pb))%>%
  ungroup()%>%
  select(-Pb)%>%
  unique()%>%
  mutate(Site_ID = case_when(SAMPLE == "PB10652.1" ~ "PB.4.10652SutterAve.1",
                             SAMPLE == "PB10652.2" ~ "PB.4.10652SutterAve.2",
                             SAMPLE == "PB10652.3" ~ "PB.4.10652SutterAve.3",
                             SAMPLE == "13070.1" ~ "PB.4.13070CarlSt443.1",
                             SAMPLE == "13070.2" ~ "PB.4.13070CarlSt443.2",
                             SAMPLE == "13070.3" ~ "PB.4.13070CarlSt443.3",
                             SAMPLE == "10600.1" ~ "PB.4.10600NSutter.1",
                             SAMPLE == "10600.2" ~ "PB.4.10600NSutter.2",
                             SAMPLE == "10600.3" ~ "PB.4.10600Nsutter.3",
                             SAMPLE == "DMGP.1" ~ "PB.4.DavidMGonzalezPark.1",
                             SAMPLE == "DMGP.2" ~ "PB.4.DavidMGonzalezPark.2",
                             SAMPLE == "DMGP.3" ~ "PB.4.DavidMGonzalezPark.3"))

```

```{r Batch Merge, message=FALSE, warning=FALSE, echo=FALSE}
BatchesMerge <- merge(merge(merge(PB_SoilBatch1_merge, Batch2_SamplesPB2022, by = "Site_ID", all.x = TRUE,
      suffixes = c(".Batch1", ".Batch2")),
      Batch3_SamplesPB2022, by = "Site_ID", all.x = TRUE, suffixes = c("", ".Batch3")),
      Batch4_SamplesPB2022, by = "Site_ID", all.x = TRUE, suffixes = c("", ".Batch4"))

BatchesMerge <- BatchesMerge%>%
    mutate(Sample = ifelse(!is.na(SAMPLE.Batch1), SAMPLE.Batch1,
                           ifelse(!is.na(SAMPLE.Batch2), SAMPLE.Batch2,
                                  ifelse(!is.na(SAMPLE), SAMPLE,
                                         ifelse(!is.na(SAMPLE.Batch4), SAMPLE.Batch4, NA)))),
           Average = ifelse(!is.na(`Average Pb (ppm)`), `Average Pb (ppm)`,
                            ifelse(!is.na(`Average (ppm)`), `Average (ppm)`,
                                   ifelse(!is.na(`Average (in ppm)`), `Average (in ppm)`,
                                          ifelse(!is.na(`Average (ppm).Batch4`), `Average (ppm).Batch4`,
                                                        NA)))))%>%
  select(!c(SAMPLE.Batch1, SAMPLE.Batch2, SAMPLE, SAMPLE.Batch4, LOCATION,
            LOCATION.Batch3, LOCATION.Batch4, Pb.Batch1, Pb.Batch2,
            `Average Pb (ppm)`, `Average (ppm)`, `Average (in ppm)`, `Average (ppm).Batch4`))

BatchesMerge$Average <- round(BatchesMerge$Average, 4)

Batch_AddEdit <- merge(BatchAdd, Pacoima_Beautiful5, all.x = TRUE)%>%
  filter(!is.na(SAMPLE))

BatchesComplete <- rbind(BatchesMerge, Batch_AddEdit%>%
                           select(Site_ID, ObjectID, GlobalID, CreationDate, Creator, EditDate,
                           Editor, `Date/Time of Collection`, `Sample ID`, Name, `Phone/email`, Address,
                           `Location of Sample`, `Other(specify) - Location of Sample`, `Other (exact location)`,
                           `Sample Area`, x, y, `editor notes`, SAMPLE, Average)%>%
                           rename(Sample = "SAMPLE"))%>%
  filter(!is.na(Average))

# write.csv(BatchesComplete, "CSVFiles/BatchesComplete.csv", row.names = FALSE)

```

```{r Merged Batches, message=FALSE, warning=FALSE, echo=FALSE}
# write.csv(BatchesMerge%>%
#             filter(!is.na(Average)), "CSVFiles/BatchesMerged_Complete.csv", row.names = FALSE)
# 
# write.csv(BatchesMerge%>%
#             filter(is.na(Average)), "CSVFiles/BatchesMerged_Incomplete.csv", row.names = FALSE)


```

```{r Leaflet Map, message=FALSE, warning=FALSE, echo=FALSE, fig.width=10, fig.height=8}
# BatchesMerged_Complete <- BatchesMerge%>%
#   filter(!is.na(Average))%>%
#   mutate(AvgCat = case_when(Average < 81 ~ "0-80",
#                             Average < 121 ~ "81-120",
#                             Average < 201 ~ "121-200",
#                             Average < 280 ~ "201-275"))

# max is 387, only plots to third category
# BatchesComplete <- BatchesComplete%>%
#   mutate(AvgCat = case_when(Average < 80 ~ "<80",
#                             Average < 300 ~ "80-299",
#                             Average < 400 ~ "300-399",
#                             Average < 1000 ~ "400-999",
#                             Average > 1000 ~ ">1000"))

BatchesComplete <- BatchesComplete%>%
  mutate(Average = round(Average, 2),
         AvgCat = case_when(Average < 91 ~ "<90",
                            Average < 121 ~ "90-120",
                            Average < 151 ~ "121-150",
                            Average < 401 ~ "151-400"),
         Pb_Cat = case_when(Average < 80 ~ "<80",
                            Average < 300 ~ "80-299",
                            Average < 400 ~ "300-399",
                            Average < 1000 ~ "400-999",
                            Average > 1000 ~ ">1000"))

BatchesComplete$AvgCat <- factor(BatchesComplete$AvgCat,
                                        levels = c("<90", "90-120", "121-150", "151-400"))

#levels = c("<80", "80-299", "300-399", "400-999", ">1000")
# BatchesComplete$AvgCat <- factor(BatchesComplete$AvgCat, 
#                                  levels = c("<80", "80-299", "300-399", "400-999", ">1000"))

pal <- colorFactor(palette = c("green", "yellow", "red", "purple"), # "#FF69B4", 
                   levels = c("<90", "90-120", "121-150", "151-400"))

leaflet(BatchesComplete)%>%
    addTiles()%>%
    addCircleMarkers(~x, ~y, popup =  ~paste0("Average (ppm) : ", Average),
                     label = ~paste0("Average (ppm) : ", Average),
                     opacity = 0.65, color = ~pal(AvgCat))%>%
    setView(lng = -118.41523986680049, lat = 34.2682767498419, zoom = 15)%>%
    addLegend(position = "bottomleft", pal = pal, values = ~AvgCat, opacity = 1, title = "Average (ppm)")

```

